<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="RaghavPC" name="AnnotationAssertionTest" tests="6" failures="1" timestamp="2 Sep 2017 06:23:48 GMT" time="1.186" errors="0">
  <testcase name="positiveTest" time="0.008" classname="testng.learning.AnnotationAssertionTest"/>
  <testcase name="doLoginTest" time="0.0" classname="testng.learning.AnnotationAssertionTest">
    <skipped/>
  </testcase> <!-- doLoginTest -->
  <testcase name="skipTest" time="0.0" classname="testng.learning.AnnotationAssertionTest">
    <skipped/>
  </testcase> <!-- skipTest -->
  <testcase name="assertTest" time="0.032" classname="testng.learning.AnnotationAssertionTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [expected] but found [actual], 
	error message reported for failure	error message reported for failure">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [expected] but found [actual], 
	error message reported for failure	error message reported for failure
	at testng.learning.AnnotationAssertionTest.assertTest(AnnotationAssertionTest.java:101)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- assertTest -->
  <testcase name="changePasswordTest" time="0.0" classname="testng.learning.AnnotationAssertionTest">
    <skipped/>
  </testcase> <!-- changePasswordTest -->
  <testcase name="logoutTest" time="0.0" classname="testng.learning.AnnotationAssertionTest">
    <skipped/>
  </testcase> <!-- logoutTest -->
</testsuite> <!-- AnnotationAssertionTest -->
